//a - scanf("%d", &valor);

//b - printf(“O produto de %d e %d é %d\n”, x, y, x*y);

//c - somaDosNumeros = primeiroNumero + segundoNumero

//d - if ( numero => maior )
//    {
//        maior == numero;
//    }

//e - scanf("%d", &umInteiro);

//f - printf(“Modulo de %d dividido por %d é %d\n”, x, y, x/y);

//g - if ( x == y );
//    {
//        printf("%d é igual a %d\n", x, y );
//    }

//h - printf("A soma é %d\n", x + y );

//i - printf("O valor que voce digitou e: %d\n", &valor);